-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
-- Modificated by Eduardo Galindo 20181006498 UNAH HN
--   at:        2024-04-10 00:16:47 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

create database RESTAURANTE;

use RESTAURANTE;

CREATE TABLE clientes (
    idcliente int primary key auto_increment,
    nombre     VARCHAR(20),
    apellido   VARCHAR(20),
    identidad  int(13),
    correo     VARCHAR(50),
    telefono   INTEGER(10)
);

CREATE TABLE clientes (
    idAdmnistrador int primary key auto_increment,
    nombre     VARCHAR(20),
    apellido   VARCHAR(20),
    identidad  int(13),
    correo     VARCHAR(50),
    telefono   INTEGER(10)
);

CREATE TABLE facturas (
    idfacturas   INT primary key auto_increment,
    fechaemision DATE
);

CREATE TABLE proveedores (
    idproveedor INTEGER primary key,
    nombre    VARCHAR(25),
    direccion VARCHAR(70),
    telefono  INTEGER,
    email     VARCHAR(50)
);


CREATE TABLE ordenes (
    idorden       INT primary key auto_increment,
    idcliente     INT,
    fechaorden    DATE,
    idfacturas 	  INT,
    foreign key(idfacturas) references facturas(idfacturas)
);


CREATE TABLE comidas (
    idcomida     varchar(5) primary key,
    idorden      int,
    nombrecomida VARCHAR(50) NOT NULL,
    tipocomida   VARCHAR(20),
    foreign key(idorden) references ordenes(idorden)
);

CREATE TABLE inventario (
    idproducto         varchar(10) primary key,
    idproveedor        INTEGER not null,
    idcomida           varchar(5) NOT NULL,
    nombreproducto     VARCHAR(30),
    categoriaproducto  VARCHAR(25),
    cantidaddisponible INTEGER,
    unidadmedida       VARCHAR(20),
    fechacaducidad     DATE,
    preciounidad       INTEGER,
    foreign key(idproveedor) references proveedores(idproveedor),
    foreign key(idcomida) references comidas(idcomida)
);


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
